url=jdbc:postgresql://172.16.100.00:5432/arcdigqa
user=postgres
password=************
driver=org.postgresql.Driver
carpeta=/home/ArcDig/ARA
host_correo=email.regionsanmartin.gob.pe
dominio=regionsanmartin.gob.pe
direccion=http://172.16.100.24:5433/ArcDigAR/
link=https://apps.regionsanmartin.gob.pe:6443/arcdigqa/


#service1=
service1=
#SIADO
siado_url=
siado_usuaro=
siado_alias=
siado_password=
sistemaid=12
siado_IdInst=5


#SIADO

#url=jdbc:postgresql://localhost:5432/ArcDigAR
#user=postgres
#password=123456
#driver=org.postgresql.Driver
#carpeta=D:/CATALOGO_AR
#host_correo=correo.regionsanmartin.gob.pe
#dominio=regionsanmartin.gob.pe
#direccion=http://localhost:8084/ArcDigAR/